#!/bin/bash

MODULE_NAME=CORE-utilities

GET_ENV_VARIABLE=$DEVOPSWORKS_ROOT/env-variables.sh

UTILITIES_HOME=$($GET_ENV_VARIABLE utilities)

FRAMEWORK_VARIABLES_FILE=$($GET_ENV_VARIABLE environment)

LOGGING=$UTILITIES_HOME/logging.sh
GET_TIMESTAMP=$UTILITIES_HOME/get-timestamp.sh
JSON=$UTILITIES_HOME/json.sh


TEMP=$($GET_ENV_VARIABLE TEMP)
PARAM_MODULE_NAME=$1
PARAM_MODULE_HOME=$($GET_ENV_VARIABLE $PARAM_MODULE_NAME)
PARAM_MODULE_VARIABLES_FILE=$PARAM_MODULE_HOME/variables.json

$LOGGING $MODULE_NAME "TEMP:$TEMP"
$LOGGING $MODULE_NAME "PARAM_MODULE_HOME:$PARAM_MODULE_HOME"
$LOGGING $MODULE_NAME "PARAM_MODULE_VARIABLES_FILE:$PARAM_MODULE_VARIABLES_FILE"



if [ ! -z $2 ]
then
  if [ $2 = "get_temp_variables_file" ]
  then
    $LOGGING $MODULE_NAME "Get temp variables file"

    TIMESTAMP=$($JSON get timestamp $PARAM_MODULE_VARIABLES_FILE)

    PARAM_MODULE_TEMP_VARIABLE_FILE=$TEMP/$PARAM_MODULE_NAME-variables.$TIMESTAMP.json

    echo $PARAM_MODULE_TEMP_VARIABLE_FILE
  fi


else
  TIMESTAMP=$($GET_TIMESTAMP)
  $JSON set timestamp \"$TIMESTAMP\" $PARAM_MODULE_VARIABLES_FILE
  PARAM_MODULE_TEMP_VARIABLE_FILE=$TEMP/$PARAM_MODULE_NAME-variables.$TIMESTAMP.json

  $LOGGING $MODULE_NAME "PARAM_MODULE_TEMP_VARIABLE_FILE:$PARAM_MODULE_TEMP_VARIABLE_FILE"

  cp "$PARAM_MODULE_VARIABLES_FILE" "$PARAM_MODULE_TEMP_VARIABLE_FILE"
  $LOGGING $MODULE_NAME "cp \"$PARAM_MODULE_VARIABLES_FILE\" \"$PARAM_MODULE_TEMP_VARIABLE_FILE\""
fi