#!/bin/bash

MODULE_NAME=FRAMEWORK-devops-dev-env

GET_ENV_VARIABLE=$DEVOPSWORKS_ROOT/env-variables.sh

UTILITIES_HOME=$($GET_ENV_VARIABLE utilities)

FRAMEWORK_VARIABLES_FILE=$($GET_ENV_VARIABLE environment)

LOGGING=$UTILITIES_HOME/logging.sh
GET_TIMESTAMP=$UTILITIES_HOME/get-timestamp.sh
CLONE_TEMP_VARIABLES_FILE=$UTILITIES_HOME/clone-temp-variables-file.sh
JSON=$UTILITIES_HOME/json.sh


$CLONE_TEMP_VARIABLES_FILE CORE_MODULE_AWS_AMI_PACKAGING

CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE=$($CLONE_TEMP_VARIABLES_FILE CORE_MODULE_AWS_AMI_PACKAGING get_temp_variables_file)

$LOGGING $MODULE_NAME "CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE:$CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE"

$JSON set aws_access_key \"AKIAISYPN2224DGOU5BQ\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE
$JSON set aws_secret_key \"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\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE

$JSON set region \"ap-southeast-1\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE
$JSON set instance_type \"m3.medium\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE

$JSON set ami_name \"devops-dev-env{{timestamp}}\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE
$JSON set ami_description \"This\ is\ generated\ from\ test\ code\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE

$JSON set resource_tag_key1 \"Department\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE
$JSON set resource_tag_value1 \"Development\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE

$JSON set scripts_src_folder \"AKIAISYPN2224DGOU5BQ\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE
$JSON set scripts_dest_folder \"PKvmv1H5QRC69laz7uhoZsWN2co04MdIz5k8emNa\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE

$JSON set provisioner_pre_local_shell \"AKIAISYPN2224DGOU5BQ\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE
$JSON set provisioner_post_local_shell \"PKvmv1H5QRC69laz7uhoZsWN2co04MdIz5k8emNa\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE

$JSON set provisioner_pre_remote_shell \"AKIAISYPN2224DGOU5BQ\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE
$JSON set provisioner_post_remote_shell \"PKvmv1H5QRC69laz7uhoZsWN2co04MdIz5k8emNa\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE

$JSON set provisioner_ansible_playbook \"AKIAISYPN2224DGOU5BQ\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE
$JSON set provisioner_ansible_variables_file \"PKvmv1H5QRC69laz7uhoZsWN2co04MdIz5k8emNa\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE

$JSON set vagrant \"AKIAISYPN2224DGOU5BQ\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE
$JSON set debug \"PKvmv1H5QRC69laz7uhoZsWN2co04MdIz5k8emNa\" $CORE_MODULE_AWS_AMI_PACKAGING_TEMP_VARIABLES_FILE