---
- hosts: localhost
  connection: local
  gather_facts: no
  become: yes

  vars_files:
  - test_vars.yml
  - configuration_vars.yml

  roles:
    - get_variables_from_git
    - setup_aws_key
    - packer

  tasks:

